version: '3'

services:
     nginx:
        container_name: nodejs
        build:
           context: .
           dockerfile: Dockerfile
        ports:
          - "80:80"
        command: npm start

